name=C++ Mode
category=Other
authors=[Jose Gonzalez Llamas](https://github.com/pepc84)
url=https://github.com/processing-cpp/processing.cpp
sentence=Write and run Processing sketches in C++.
paragraph=Processing C++ Mode is an implementation of the Processing programming environment for C++, allowing users to write Processing-style sketches that compile to native C++.
version=17
prettyVersion=0.4.7
minRevision=1280
maxRevision=0
